version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=bunker1
      - POSTGRES_PASSWORD=bunker1234
      - POSTGRES_DB=bunkerapp-db
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bunkerapp
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: bunkerapp-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db

  cache:
    image: redis:6
    env_file:
      - .env
    ports:
      - '6379:6379'

  redisinsight:
    image: redislabs/redisinsight
    ports:
      - '8001:8001'
volumes:
  postgres_data:
